spring:
  application:
    name: customer-service
  profiles:
    include: feign,tomcat,jersey,nacos,jpa,common,actuator
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: messages/message
    use-code-as-default-message: true
    encoding: utf-8