#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@10.0.250.175:1521/bosspdb
#    username: boss_system
#    password: boss_system


star:
  url: localhost
#  启动端口
  tomcat-port: ${star.port.${spring.application.name}}
  port:
    partner-service: ${star.server.port:11111}
    customer-service: ${star.server.port:11112}
