feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        contract: feign.jaxrs.JAXRSContract  # feign使用JAX-RS定义的接口
        connectTimeout: 60000
        readTimeout: 60000
      jaxrs:
        contract: feign.jaxrs.JAXRSContract  # feign使用JAX-RS定义的接口
        connectTimeout: 60000
        readTimeout: 60000