server:
  port: ${star.tomcat-port:8080}
  servlet:
    application-display-name: ${spring.application.name:no-domain}
    context-path: /
    session:
      cookie:
        path: /
  tomcat:
    accept-count: 1000
    max-threads: 1000
    connection-timeout: 60s
#    accesslog:
#      enabled: false
#    mbeanregistry:
#      enabled: true

#---
#spring:
#  profiles: dev-f1
#star:
#  url: localhost
#  #  启动端口
#  tomcat-port: ${star.port.${spring.application.name}}
#  port:
#    partner-service: ${star.server.port:11111}
#    customer-service: ${star.server.port:11112}
